import type { StrategyFactorCatalogState, StrategyFoundationState, StrategyTemplate } from './strategy-types';

export const SAMPLE_UNIVERSE_ID = 'a-share-sample-research-pool';

export const SAMPLE_UNIVERSE_MEMBER_SEEDS = [
  { symbol: '002156.SZ', code: '002156', name: '通富微电', exchange: 'SZ', secid: '0.002156' },
  { symbol: '002555.SZ', code: '002555', name: '三七互娱', exchange: 'SZ', secid: '0.002555' },
  { symbol: '002624.SZ', code: '002624', name: '完美世界', exchange: 'SZ', secid: '0.002624' },
  { symbol: '601398.SH', code: '601398', name: '工商银行', exchange: 'SH', secid: '1.601398' },
  { symbol: '600916.SH', code: '600916', name: '中国黄金', exchange: 'SH', secid: '1.600916' },
  { symbol: '600519.SH', code: '600519', name: '贵州茅台', exchange: 'SH', secid: '1.600519' },
  { symbol: '000858.SZ', code: '000858', name: '五粮液', exchange: 'SZ', secid: '0.000858' },
  { symbol: '000333.SZ', code: '000333', name: '美的集团', exchange: 'SZ', secid: '0.000333' },
  { symbol: '000651.SZ', code: '000651', name: '格力电器', exchange: 'SZ', secid: '0.000651' },
  { symbol: '300750.SZ', code: '300750', name: '宁德时代', exchange: 'SZ', secid: '0.300750' },
  { symbol: '002594.SZ', code: '002594', name: '比亚迪', exchange: 'SZ', secid: '0.002594' },
  { symbol: '601318.SH', code: '601318', name: '中国平安', exchange: 'SH', secid: '1.601318' },
  { symbol: '600036.SH', code: '600036', name: '招商银行', exchange: 'SH', secid: '1.600036' },
  { symbol: '601166.SH', code: '601166', name: '兴业银行', exchange: 'SH', secid: '1.601166' },
  { symbol: '601288.SH', code: '601288', name: '农业银行', exchange: 'SH', secid: '1.601288' },
  { symbol: '600900.SH', code: '600900', name: '长江电力', exchange: 'SH', secid: '1.600900' },
  { symbol: '601012.SH', code: '601012', name: '隆基绿能', exchange: 'SH', secid: '1.601012' },
  { symbol: '600276.SH', code: '600276', name: '恒瑞医药', exchange: 'SH', secid: '1.600276' },
  { symbol: '000725.SZ', code: '000725', name: '京东方A', exchange: 'SZ', secid: '0.000725' },
  { symbol: '002415.SZ', code: '002415', name: '海康威视', exchange: 'SZ', secid: '0.002415' },
  { symbol: '600050.SH', code: '600050', name: '中国联通', exchange: 'SH', secid: '1.600050' },
  { symbol: '601857.SH', code: '601857', name: '中国石油', exchange: 'SH', secid: '1.601857' },
  { symbol: '600028.SH', code: '600028', name: '中国石化', exchange: 'SH', secid: '1.600028' },
  { symbol: '601668.SH', code: '601668', name: '中国建筑', exchange: 'SH', secid: '1.601668' },
  { symbol: '601888.SH', code: '601888', name: '中国中免', exchange: 'SH', secid: '1.601888' },
  { symbol: '600030.SH', code: '600030', name: '中信证券', exchange: 'SH', secid: '1.600030' },
  { symbol: '300059.SZ', code: '300059', name: '东方财富', exchange: 'SZ', secid: '0.300059' },
  { symbol: '603259.SH', code: '603259', name: '药明康德', exchange: 'SH', secid: '1.603259' },
  { symbol: '688981.SH', code: '688981', name: '中芯国际', exchange: 'SH', secid: '1.688981' },
  { symbol: '002230.SZ', code: '002230', name: '科大讯飞', exchange: 'SZ', secid: '0.002230' },
  { symbol: '603986.SH', code: '603986', name: '兆易创新', exchange: 'SH', secid: '1.603986' },
  { symbol: '603501.SH', code: '603501', name: '韦尔股份', exchange: 'SH', secid: '1.603501' },
  { symbol: '002371.SZ', code: '002371', name: '北方华创', exchange: 'SZ', secid: '0.002371' },
  { symbol: '688012.SH', code: '688012', name: '中微公司', exchange: 'SH', secid: '1.688012' },
  { symbol: '600584.SH', code: '600584', name: '长电科技', exchange: 'SH', secid: '1.600584' },
  { symbol: '688008.SH', code: '688008', name: '澜起科技', exchange: 'SH', secid: '1.688008' },
  { symbol: '688126.SH', code: '688126', name: '沪硅产业', exchange: 'SH', secid: '1.688126' },
  { symbol: '688099.SH', code: '688099', name: '晶晨股份', exchange: 'SH', secid: '1.688099' },
  { symbol: '300223.SZ', code: '300223', name: '北京君正', exchange: 'SZ', secid: '0.300223' },
  { symbol: '603290.SH', code: '603290', name: '斯达半导', exchange: 'SH', secid: '1.603290' },
  { symbol: '300661.SZ', code: '300661', name: '圣邦股份', exchange: 'SZ', secid: '0.300661' },
  { symbol: '300782.SZ', code: '300782', name: '卓胜微', exchange: 'SZ', secid: '0.300782' },
  { symbol: '002049.SZ', code: '002049', name: '紫光国微', exchange: 'SZ', secid: '0.002049' },
  { symbol: '600745.SH', code: '600745', name: '闻泰科技', exchange: 'SH', secid: '1.600745' },
  { symbol: '605358.SH', code: '605358', name: '立昂微', exchange: 'SH', secid: '1.605358' },
  { symbol: '688396.SH', code: '688396', name: '华润微', exchange: 'SH', secid: '1.688396' },
  { symbol: '688041.SH', code: '688041', name: '海光信息', exchange: 'SH', secid: '1.688041' },
  { symbol: '688256.SH', code: '688256', name: '寒武纪', exchange: 'SH', secid: '1.688256' },
  { symbol: '688111.SH', code: '688111', name: '金山办公', exchange: 'SH', secid: '1.688111' },
  { symbol: '688036.SH', code: '688036', name: '传音控股', exchange: 'SH', secid: '1.688036' },
  { symbol: '688521.SH', code: '688521', name: '芯原股份', exchange: 'SH', secid: '1.688521' },
  { symbol: '002475.SZ', code: '002475', name: '立讯精密', exchange: 'SZ', secid: '0.002475' },
  { symbol: '601138.SH', code: '601138', name: '工业富联', exchange: 'SH', secid: '1.601138' },
  { symbol: '300308.SZ', code: '300308', name: '中际旭创', exchange: 'SZ', secid: '0.300308' },
  { symbol: '300502.SZ', code: '300502', name: '新易盛', exchange: 'SZ', secid: '0.300502' },
  { symbol: '300394.SZ', code: '300394', name: '天孚通信', exchange: 'SZ', secid: '0.300394' },
  { symbol: '000977.SZ', code: '000977', name: '浪潮信息', exchange: 'SZ', secid: '0.000977' },
  { symbol: '603019.SH', code: '603019', name: '中科曙光', exchange: 'SH', secid: '1.603019' },
  { symbol: '000938.SZ', code: '000938', name: '紫光股份', exchange: 'SZ', secid: '0.000938' },
  { symbol: '002463.SZ', code: '002463', name: '沪电股份', exchange: 'SZ', secid: '0.002463' },
  { symbol: '300033.SZ', code: '300033', name: '同花顺', exchange: 'SZ', secid: '0.300033' },
  { symbol: '600570.SH', code: '600570', name: '恒生电子', exchange: 'SH', secid: '1.600570' },
  { symbol: '600588.SH', code: '600588', name: '用友网络', exchange: 'SH', secid: '1.600588' },
  { symbol: '002410.SZ', code: '002410', name: '广联达', exchange: 'SZ', secid: '0.002410' },
  { symbol: '002236.SZ', code: '002236', name: '大华股份', exchange: 'SZ', secid: '0.002236' },
  { symbol: '002241.SZ', code: '002241', name: '歌尔股份', exchange: 'SZ', secid: '0.002241' },
  { symbol: '300124.SZ', code: '300124', name: '汇川技术', exchange: 'SZ', secid: '0.300124' },
  { symbol: '688777.SH', code: '688777', name: '中控技术', exchange: 'SH', secid: '1.688777' },
  { symbol: '300496.SZ', code: '300496', name: '中科创达', exchange: 'SZ', secid: '0.300496' },
  { symbol: '002920.SZ', code: '002920', name: '德赛西威', exchange: 'SZ', secid: '0.002920' },
  { symbol: '000063.SZ', code: '000063', name: '中兴通讯', exchange: 'SZ', secid: '0.000063' },
  { symbol: '600941.SH', code: '600941', name: '中国移动', exchange: 'SH', secid: '1.600941' },
  { symbol: '300604.SZ', code: '300604', name: '长川科技', exchange: 'SZ', secid: '0.300604' },
  { symbol: '688037.SH', code: '688037', name: '芯源微', exchange: 'SH', secid: '1.688037' },
  { symbol: '688072.SH', code: '688072', name: '拓荆科技', exchange: 'SH', secid: '1.688072' },
  { symbol: '688082.SH', code: '688082', name: '盛美上海', exchange: 'SH', secid: '1.688082' },
  { symbol: '688120.SH', code: '688120', name: '华海清科', exchange: 'SH', secid: '1.688120' },
  { symbol: '688200.SH', code: '688200', name: '华峰测控', exchange: 'SH', secid: '1.688200' },
  { symbol: '688019.SH', code: '688019', name: '安集科技', exchange: 'SH', secid: '1.688019' },
  { symbol: '688234.SH', code: '688234', name: '天岳先进', exchange: 'SH', secid: '1.688234' },
  { symbol: '300666.SZ', code: '300666', name: '江丰电子', exchange: 'SZ', secid: '0.300666' },
  { symbol: '002409.SZ', code: '002409', name: '雅克科技', exchange: 'SZ', secid: '0.002409' },
  { symbol: '688536.SH', code: '688536', name: '思瑞浦', exchange: 'SH', secid: '1.688536' },
  { symbol: '688052.SH', code: '688052', name: '纳芯微', exchange: 'SH', secid: '1.688052' },
  { symbol: '688798.SH', code: '688798', name: '艾为电子', exchange: 'SH', secid: '1.688798' },
  { symbol: '688608.SH', code: '688608', name: '恒玄科技', exchange: 'SH', secid: '1.688608' },
  { symbol: '688385.SH', code: '688385', name: '复旦微电', exchange: 'SH', secid: '1.688385' },
  { symbol: '688107.SH', code: '688107', name: '安路科技', exchange: 'SH', secid: '1.688107' },
  { symbol: '688153.SH', code: '688153', name: '唯捷创芯', exchange: 'SH', secid: '1.688153' },
  { symbol: '688213.SH', code: '688213', name: '思特威', exchange: 'SH', secid: '1.688213' },
  { symbol: '688220.SH', code: '688220', name: '翱捷科技', exchange: 'SH', secid: '1.688220' },
  { symbol: '301269.SZ', code: '301269', name: '华大九天', exchange: 'SZ', secid: '0.301269' },
  { symbol: '688262.SH', code: '688262', name: '国芯科技', exchange: 'SH', secid: '1.688262' },
  { symbol: '688047.SH', code: '688047', name: '龙芯中科', exchange: 'SH', secid: '1.688047' },
  { symbol: '688502.SH', code: '688502', name: '茂莱光学', exchange: 'SH', secid: '1.688502' },
  { symbol: '688498.SH', code: '688498', name: '源杰科技', exchange: 'SH', secid: '1.688498' },
  { symbol: '300567.SZ', code: '300567', name: '精测电子', exchange: 'SZ', secid: '0.300567' },
  { symbol: '002916.SZ', code: '002916', name: '深南电路', exchange: 'SZ', secid: '0.002916' },
  { symbol: '002938.SZ', code: '002938', name: '鹏鼎控股', exchange: 'SZ', secid: '0.002938' },
  { symbol: '002384.SZ', code: '002384', name: '东山精密', exchange: 'SZ', secid: '0.002384' },
  { symbol: '300476.SZ', code: '300476', name: '胜宏科技', exchange: 'SZ', secid: '0.300476' },
  { symbol: '603228.SH', code: '603228', name: '景旺电子', exchange: 'SH', secid: '1.603228' },
  { symbol: '603160.SH', code: '603160', name: '汇顶科技', exchange: 'SH', secid: '1.603160' },
  { symbol: '002138.SZ', code: '002138', name: '顺络电子', exchange: 'SZ', secid: '0.002138' },
  { symbol: '600183.SH', code: '600183', name: '生益科技', exchange: 'SH', secid: '1.600183' },
  { symbol: '300408.SZ', code: '300408', name: '三环集团', exchange: 'SZ', secid: '0.300408' },
  { symbol: '002402.SZ', code: '002402', name: '和而泰', exchange: 'SZ', secid: '0.002402' },
  { symbol: '002139.SZ', code: '002139', name: '拓邦股份', exchange: 'SZ', secid: '0.002139' },
  { symbol: '002050.SZ', code: '002050', name: '三花智控', exchange: 'SZ', secid: '0.002050' },
  { symbol: '002747.SZ', code: '002747', name: '埃斯顿', exchange: 'SZ', secid: '0.002747' },
  { symbol: '300024.SZ', code: '300024', name: '机器人', exchange: 'SZ', secid: '0.300024' },
  { symbol: '688017.SH', code: '688017', name: '绿的谐波', exchange: 'SH', secid: '1.688017' },
  { symbol: '301029.SZ', code: '301029', name: '怡合达', exchange: 'SZ', secid: '0.301029' },
  { symbol: '688188.SH', code: '688188', name: '柏楚电子', exchange: 'SH', secid: '1.688188' },
  { symbol: '300316.SZ', code: '300316', name: '晶盛机电', exchange: 'SZ', secid: '0.300316' },
  { symbol: '002008.SZ', code: '002008', name: '大族激光', exchange: 'SZ', secid: '0.002008' },
  { symbol: '300450.SZ', code: '300450', name: '先导智能', exchange: 'SZ', secid: '0.300450' },
  { symbol: '688187.SH', code: '688187', name: '时代电气', exchange: 'SH', secid: '1.688187' },
  { symbol: '688169.SH', code: '688169', name: '石头科技', exchange: 'SH', secid: '1.688169' },
  { symbol: '000066.SZ', code: '000066', name: '中国长城', exchange: 'SZ', secid: '0.000066' },
  { symbol: '002439.SZ', code: '002439', name: '启明星辰', exchange: 'SZ', secid: '0.002439' },
  { symbol: '300454.SZ', code: '300454', name: '深信服', exchange: 'SZ', secid: '0.300454' },
  { symbol: '300017.SZ', code: '300017', name: '网宿科技', exchange: 'SZ', secid: '0.300017' },
  { symbol: '002405.SZ', code: '002405', name: '四维图新', exchange: 'SZ', secid: '0.002405' },
  { symbol: '002212.SZ', code: '002212', name: '天融信', exchange: 'SZ', secid: '0.002212' },
  { symbol: '688568.SH', code: '688568', name: '中科星图', exchange: 'SH', secid: '1.688568' },
  { symbol: '688088.SH', code: '688088', name: '虹软科技', exchange: 'SH', secid: '1.688088' },
  { symbol: '300229.SZ', code: '300229', name: '拓尔思', exchange: 'SZ', secid: '0.300229' },
  { symbol: '300418.SZ', code: '300418', name: '昆仑万维', exchange: 'SZ', secid: '0.300418' },
  { symbol: '300413.SZ', code: '300413', name: '芒果超媒', exchange: 'SZ', secid: '0.300413' },
  { symbol: '603000.SH', code: '603000', name: '人民网', exchange: 'SH', secid: '1.603000' },
  { symbol: '601360.SH', code: '601360', name: '三六零', exchange: 'SH', secid: '1.601360' },
  { symbol: '002602.SZ', code: '002602', name: '世纪华通', exchange: 'SZ', secid: '0.002602' },
  { symbol: '300315.SZ', code: '300315', name: '掌趣科技', exchange: 'SZ', secid: '0.300315' },
  { symbol: '000001.SZ', code: '000001', name: '平安银行', exchange: 'SZ', secid: '0.000001' },
  { symbol: '600000.SH', code: '600000', name: '浦发银行', exchange: 'SH', secid: '1.600000' },
  { symbol: '601939.SH', code: '601939', name: '建设银行', exchange: 'SH', secid: '1.601939' },
  { symbol: '601988.SH', code: '601988', name: '中国银行', exchange: 'SH', secid: '1.601988' },
  { symbol: '601328.SH', code: '601328', name: '交通银行', exchange: 'SH', secid: '1.601328' },
  { symbol: '601658.SH', code: '601658', name: '邮储银行', exchange: 'SH', secid: '1.601658' },
  { symbol: '600999.SH', code: '600999', name: '招商证券', exchange: 'SH', secid: '1.600999' },
  { symbol: '601211.SH', code: '601211', name: '国泰君安', exchange: 'SH', secid: '1.601211' },
  { symbol: '601688.SH', code: '601688', name: '华泰证券', exchange: 'SH', secid: '1.601688' },
  { symbol: '000776.SZ', code: '000776', name: '广发证券', exchange: 'SZ', secid: '0.000776' },
  { symbol: '601601.SH', code: '601601', name: '中国太保', exchange: 'SH', secid: '1.601601' },
  { symbol: '601336.SH', code: '601336', name: '新华保险', exchange: 'SH', secid: '1.601336' },
  { symbol: '000568.SZ', code: '000568', name: '泸州老窖', exchange: 'SZ', secid: '0.000568' },
  { symbol: '600809.SH', code: '600809', name: '山西汾酒', exchange: 'SH', secid: '1.600809' },
  { symbol: '603369.SH', code: '603369', name: '今世缘', exchange: 'SH', secid: '1.603369' },
  { symbol: '600887.SH', code: '600887', name: '伊利股份', exchange: 'SH', secid: '1.600887' },
] as const;

export const FALLBACK_FOUNDATION_STATE: StrategyFoundationState = {
  source: 'fallback',
  components: [
    {
      id: 'trading-calendar',
      name: '交易日历',
      status: 'partial',
      count: 0,
      detail: '未读取到后端日历，页面会回退到本地 K 线日期推断。',
    },
    {
      id: 'factor-registry',
      name: '因子定义仓库',
      status: 'partial',
      count: 0,
      detail: '因子口径表未读取，策略仍可使用内置说明。',
    },
    {
      id: 'data-quality',
      name: '数据质量扫描',
      status: 'partial',
      count: 0,
      detail: '质量扫描 API 暂不可用。',
    },
    {
      id: 'platform-jobs',
      name: '平台任务底座',
      status: 'partial',
      count: 0,
      detail: '任务表未读取。',
    },
  ],
  factors: [],
  calendarDays: [],
  latestQualityScan: null,
  error: null,
};

export const STRATEGY_BACKTEST_DEPENDENCIES = [
  'GET /api/v1/research/universes/{id}/members',
  'GET /api/v1/research/bars/{symbol}',
  'GET /api/v1/indicators/technical/{symbol}',
  'GET /api/v1/backtests/strategies/{strategy_id}/{symbol}',
];
export const STRATEGY_COMMON_RISK_CONTROLS = [
  '单标的 long/flat，全仓或空仓，不使用杠杆',
  '所有扫描必须展示最大回撤、胜率、交易次数和夏普',
  '不把回测收益当作预测结论，必须说明滑点、停牌、冲击成本和分红再投资限制',
];
export const STRATEGY_COMMON_LIMITATIONS = [
  '当前策略为日线级单标的回测，组合轮动、资金容量和撮合细节后续单独建模。',
  '交易按收盘价切换仓位，暂未建模盘中触发、涨跌停无法成交和税费差异。',
];
export const STRATEGY_SELECTION_RISK_CONTROLS = [
  '选股结果必须输出命中日期、触发条件、排序分数和被剔除原因。',
  '默认剔除 ST、退市风险、ETF/指数、科创板、北证，避免涨跌幅规则混杂。',
  '任何包含 DDE/大单净量的策略必须标明数据源、更新时间和缺失覆盖率。',
  '不得把单日命中当作买入建议，必须叠加入场价格、止损和仓位约束。',
];
export const STRATEGY_PRICE_RISK_CONTROLS = [
  '先定义最大亏损和失效条件，再反推买入价格区间。',
  '买入区间必须同时给出止损、第一止盈、趋势卖出和失败退出。',
  '不追涨停成交，不在流动性不足或一字板无法成交时生成买入建议。',
  '价格策略默认只服务已经通过选股策略的候选标的。',
];
export const STRATEGY_SELECTION_LIMITATIONS = [
  '当前可直接复用日线 OHLCV、成交额、换手、涨跌停、ST 与板块标签；DDE 大单金额/大单净量仍需落库后才能全自动筛选。',
  '日线策略无法还原盘中排板、撤单和集合竞价细节，真实交易需接入分钟线或盘口数据。',
];
export const STRATEGY_PRICE_LIMITATIONS = [
  '当前买卖价格策略以日线和技术指标为主，暂未模拟盘口深度、滑点、排队成交和隔夜公告风险。',
  '策略输出是交易计划口径，不应替代人工确认基本面、消息面和当日市场环境。',
];
export const STRATEGY_OHLCV_DATA_READY = [
  '日线 open/high/low/close/volume/amount',
  '涨跌幅、涨跌额、换手率',
  '涨停/跌停推导字段',
  'ST、交易所、板块/概念标签',
  'MA5/10/20/30/60、ATR、区间高低点可计算',
];
export const STRATEGY_DDE_DATA_MISSING = [
  'DDE 大单金额',
  'DDE 大单净量',
  '近 3/5 日 DDE 聚合',
  '当日实时 DDE 更新时间',
];

export const STRATEGY_FACTOR_CATALOG: StrategyFactorCatalogState = {
  source: 'built-in-research',
  methodology: [
    '先用学术和指数公司的主流因子框架做骨架：动量、价值、质量、低波、规模、股息/现金回报。',
    '再按 A 股短中期交易特点补充可成交性、涨跌停、ST、行业/概念热度和资金流连续性。',
    '所有因子必须区分“可直接计算”“部分可用”“需要补数”，缺失不能默认为 0。',
    '组合因子只做排序和候选降权，不直接给确定性买卖结论；最终仍要经过回测、交易成本和风控约束。',
  ],
  workflow: [
    {
      id: 'data-inventory',
      stage: '01',
      title: '先盘点数据',
      objective: '确认现有数据表、字段完整性、覆盖时间、复权口径和缺口，避免用不存在或不稳定的字段设计因子。',
      inputs: ['quant.stock_bars', 'quant.stock_factors', 'quant.securities', 'security_universe_members', 'data_quality_scans'],
      outputs: ['可直接计算的字段清单', '缺失字段清单', '优先补数路线', '不可用于策略的风险字段'],
      qualityGate: '字段覆盖率、最新交易日、样本长度和缺失值处理规则都明确后，才能进入因子设计。',
    },
    {
      id: 'factor-design',
      stage: '02',
      title: '再设计因子',
      objective: '从可验证的数据出发，设计可解释、可排序、可回测的因子，并标记方向、质量和落地状态。',
      inputs: ['数据盘点结果', '主流因子框架', 'A 股交易规则', '已有策略模板需求'],
      outputs: ['因子公式', '数据依赖', '方向定义', '落地质量', '入库或批处理计划'],
      qualityGate: '因子必须可复算、可解释、可标记缺口；缺数据因子保持 needs_data，不允许用 0 或 mock 值通过。',
    },
    {
      id: 'strategy-composition',
      stage: '03',
      title: '最后组合策略',
      objective: '将多个因子组合成选股、买卖价格或风险控制策略，并通过样本内外、费用和风控验证。',
      inputs: ['可用因子', '部分可用因子', '策略模板', '回测引擎', '交易成本模型'],
      outputs: ['候选排序规则', '入场/退出规则', '参数扫描矩阵', '回测和风险报告'],
      qualityGate: '策略必须输出触发条件、排序理由、剔除原因、止损/目标价和回测限制，不能只输出推荐列表。',
    },
  ],
  dataLayers: [
    {
      id: 'daily-bars',
      name: '日线行情与交易字段',
      status: 'ready',
      priority: 'P0',
      tables: ['quant.stock_bars'],
      availableData: ['open/high/low/close', 'volume/amount/turnover', 'change_percent', 'trade_status/is_st', 'limit_up/limit_down'],
      factorIdeas: ['相对强弱', '均线多头质量', '突破确认', '实现波动率', '最大回撤', '成交额放大倍数'],
      dataGaps: ['分钟线承接', '盘口封单', '集合竞价成交额'],
      nextAction: '先把日频衍生因子批量写入 stock_factors 或截面 rank 表，支撑股票池分页排序和宽域选股。',
    },
    {
      id: 'security-master',
      name: '证券主数据与股票池关系',
      status: 'ready',
      priority: 'P0',
      tables: ['quant.securities', 'quant.security_universes', 'quant.security_universe_members'],
      availableData: ['股票/ETF/指数边界', '交易所', '资产类型', '板块/概念标签', '成员关系'],
      factorIdeas: ['行业内强弱', '板块热度', '可交易性过滤', 'ETF/个股分层策略'],
      dataGaps: ['历史行业成分', '申万/中信行业映射', '板块成分变更日期'],
      nextAction: '先保证股票池和 ETF/指数池不混用，再补行业历史映射和行业内 rank。',
    },
    {
      id: 'valuation-factors',
      name: '估值快照',
      status: 'partial',
      priority: 'P1',
      tables: ['quant.stock_factors'],
      availableData: ['pe_ttm', 'pb_mrq', 'ps_ttm', 'pcf_ncf_ttm'],
      factorIdeas: ['复合估值便宜度', '行业中性估值', '估值风险提示'],
      dataGaps: ['全市场覆盖率', '行业中位数', '极端值 winsorize', 'ETF/指数空值规则'],
      nextAction: '继续低频补齐 Baostock 估值字段，再做行业中性化和极端值处理。',
    },
    {
      id: 'financial-quality',
      name: '财报质量与成长',
      status: 'needs_data',
      priority: 'P1',
      tables: ['quant.financial_statements', 'quant.financial_indicators'],
      availableData: ['少量 provider 可解析字段，尚未形成稳定表'],
      factorIdeas: ['盈利质量', '成长加速度', '现金流质量', '资产负债率风险'],
      dataGaps: ['ROE_TTM', '毛利率', '净利率', '营收同比', '净利润同比', '经营现金流/净利润', '公告披露日'],
      nextAction: '补财报表和披露日生效规则，防止未来函数，再接入质量/成长因子。',
    },
    {
      id: 'capital-flow',
      name: '资金流与盘口事件',
      status: 'needs_data',
      priority: 'P1',
      tables: ['quant.capital_flow_daily', 'quant.intraday_bars', 'quant.limit_event_snapshots'],
      availableData: ['板块资金代理：成交额、涨跌占比、强弱和方向额'],
      factorIdeas: ['主力资金连续性', 'DDE 大单净额', '封单强度', '炸板风险', '板块资金热度'],
      dataGaps: ['主力净流入', '超大单净额', 'DDE 大单净量', '封单金额', '炸板次数', '分钟线成交分布'],
      nextAction: '优先调研可授权资金流源；代理口径只做提示，不等价为真实主力净流入。',
    },
  ],
  categories: [
    {
      id: 'momentum-trend',
      name: '趋势与动量',
      description: '用价格强弱、均线结构和突破质量捕捉短中期相对强势。',
      factors: [
        {
          id: 'relative-strength-20-60',
          name: '20/60 日相对强弱',
          category: '趋势与动量',
          horizon: '20-60 交易日',
          direction: 'higher_is_better',
          status: 'ready',
          priority: 1,
          formula: 'rank(ret_20d) * 0.6 + rank(ret_60d) * 0.4，ret_N = close / close_N_days_ago - 1',
          rationale: '短中期强者恒强是 A 股题材和趋势行情里最先落地的排序信号，适合和流动性、涨跌停可成交性一起用。',
          currentData: ['quant.stock_bars.close', 'quant.security_universe_members'],
          missingData: ['行业内相对强弱基准'],
          enrichmentPlan: ['为每个交易日写入 ret_20d、ret_60d 和行业内 rank。'],
          useCases: ['短线候选排序', '趋势突破策略过滤', '板块龙头识别'],
          guardrails: ['连续涨停或一字板需要标记不可成交。', '强弱因子必须叠加最大回撤和成交额，避免只追高。'],
          sourceFrameworks: ['MSCI Momentum', 'S&P Momentum'],
        },
        {
          id: 'ma-stack-quality',
          name: '均线多头质量',
          category: '趋势与动量',
          horizon: '5-60 交易日',
          direction: 'higher_is_better',
          status: 'ready',
          priority: 2,
          formula: 'I(MA5>MA10>MA20>MA30>MA60) + normalized(close/MA20 - 1) - overheat_penalty',
          rationale: '均线排列能把趋势状态变成稳定的可解释信号，比单日涨幅更不容易被噪声误导。',
          currentData: ['quant.stock_bars.close', 'MA5/10/20/30/60 可计算'],
          missingData: [],
          enrichmentPlan: ['将 MA 栈、乖离率、过热惩罚每日落到 stock_factors。'],
          useCases: ['强趋势筛选', '买入价格计划', '卖出破位判断'],
          guardrails: ['均线信号滞后，震荡市需结合 ATR 或布林带过滤。'],
          sourceFrameworks: ['Technical trend following'],
        },
        {
          id: 'breakout-confirmation',
          name: '突破确认质量',
          category: '趋势与动量',
          horizon: '20 交易日',
          direction: 'higher_is_better',
          status: 'ready',
          priority: 3,
          formula: 'I(close > rolling_high_20) + amount_ratio_20d + close_position_in_range',
          rationale: '有效突破通常需要价格创阶段新高、成交额同步放大，并且收盘位置不能太弱。',
          currentData: ['quant.stock_bars.high', 'quant.stock_bars.low', 'quant.stock_bars.close', 'quant.stock_bars.amount'],
          missingData: ['盘中突破回落幅度'],
          enrichmentPlan: ['后续接入分钟线后补充 intraday_breakout_fail_ratio。'],
          useCases: ['放量突破', '涨停回踩再启动', '短线买点过滤'],
          guardrails: ['当日涨停无法成交时不应作为直接买入候选。'],
          sourceFrameworks: ['Price momentum', 'Volume-price confirmation'],
        },
      ],
    },
    {
      id: 'risk-liquidity',
      name: '风险与流动性',
      description: '控制回撤、波动和可成交性，避免策略只挑出看起来强但无法交易的样本。',
      factors: [
        {
          id: 'realized-volatility-20',
          name: '20 日实现波动率',
          category: '风险与流动性',
          horizon: '20 交易日',
          direction: 'lower_is_better',
          status: 'ready',
          priority: 1,
          formula: 'stddev(daily_return, 20) * sqrt(252)',
          rationale: '低波动/风险控制因子可帮助降低组合回撤，也能约束短线追高后的尾部风险。',
          currentData: ['quant.stock_bars.close'],
          missingData: [],
          enrichmentPlan: ['按交易日批量写入 realized_vol_20d、realized_vol_60d。'],
          useCases: ['低波趋势持有', '候选股风险降权', '仓位权重'],
          guardrails: ['低波不等于低风险，停牌、跌停和流动性缺失要单独扣分。'],
          sourceFrameworks: ['MSCI Low Volatility', 'S&P Low Volatility'],
        },
        {
          id: 'max-drawdown-60',
          name: '60 日最大回撤',
          category: '风险与流动性',
          horizon: '60 交易日',
          direction: 'lower_is_better',
          status: 'ready',
          priority: 2,
          formula: 'min(close / rolling_max(close, 60) - 1)',
          rationale: '短中期最大回撤比波动率更直接地描述持有体验，适合作为追涨策略的硬过滤。',
          currentData: ['quant.stock_bars.close'],
          missingData: [],
          enrichmentPlan: ['写入 drawdown_60d 和 drawdown_120d，供股票池和回测复用。'],
          useCases: ['风险过滤', '止损参数扫描', '组合候选降权'],
          guardrails: ['历史回撤小可能只是样本太短，需要最小样本数。'],
          sourceFrameworks: ['Risk control'],
        },
        {
          id: 'liquidity-amount-turnover',
          name: '成交额与换手活跃度',
          category: '风险与流动性',
          horizon: '5-20 交易日',
          direction: 'middle_is_better',
          status: 'ready',
          priority: 3,
          formula: 'rank(avg_amount_20d) + rank(avg_turnover_20d) - extreme_turnover_penalty',
          rationale: '成交额决定策略容量，换手率反映筹码交换；两者一起比单看成交量更可比。',
          currentData: ['quant.stock_bars.amount', 'quant.stock_bars.turnover', 'quant.stock_bars.volume'],
          missingData: ['部分早期样本的自由流通股本口径'],
          enrichmentPlan: ['继续用 Baostock/EastMoney 补齐 amount、turnover；后续补流通股本快照。'],
          useCases: ['股票池排序', '资金流代理', '剔除低成交额候选'],
          guardrails: ['极端高换手叠加放量阴线往往是风险，不应简单加分。'],
          sourceFrameworks: ['Liquidity risk', 'A-share tradability'],
        },
      ],
    },
    {
      id: 'value-quality-growth',
      name: '估值、质量与成长',
      description: '把价格因子和基本面因子拆开，支持短中期交易之外的质量过滤。',
      factors: [
        {
          id: 'value-composite',
          name: '复合估值便宜度',
          category: '估值、质量与成长',
          horizon: '日频快照 + 财报期',
          direction: 'higher_is_better',
          status: 'partial',
          priority: 1,
          formula: 'z(-PE_TTM) + z(-PB_MRQ) + z(-PS_TTM) + z(-PCF_NCF_TTM)',
          rationale: '单一估值指标容易失真，组合估值更适合跨行业做降权或观察，而不是直接买入。',
          currentData: ['quant.stock_factors.pe_ttm', 'quant.stock_factors.pb_mrq', 'quant.stock_factors.ps_ttm', 'quant.stock_factors.pcf_ncf_ttm'],
          missingData: ['全股票池估值覆盖率', '行业中位数估值', '负值和极端值 winsorize 规则'],
          enrichmentPlan: ['继续用 Baostock 全量补估值因子；增加行业内 z-score 和 winsorize。'],
          useCases: ['价值过滤', '质量价值动量综合分', '估值风险提示'],
          guardrails: ['银行、周期、成长股估值口径差异大，必须行业中性化。'],
          sourceFrameworks: ['Fama-French Value', 'MSCI Value', 'S&P Value'],
        },
        {
          id: 'profitability-quality',
          name: '盈利质量',
          category: '估值、质量与成长',
          horizon: '季度/年度财报',
          direction: 'higher_is_better',
          status: 'needs_data',
          priority: 2,
          formula: 'z(ROE_TTM) + z(gross_margin) + z(net_margin) - z(debt_to_asset)',
          rationale: 'Fama-French 盈利能力和 AQR 质量因子都强调盈利、稳健和可持续性，是中期持有最值得补的数据。',
          currentData: ['部分股票可通过 fundamentals/provider 补财报字段'],
          missingData: ['ROE_TTM', '毛利率', '净利率', '资产负债率', '经营现金流/净利润'],
          enrichmentPlan: ['接入 AKShare/Baostock 财报端点或 Tushare Pro 授权源，落库 quant.financial_statements 与 quant.financial_indicators。'],
          useCases: ['中期持有过滤', '高质量低估筛选', '避开题材垃圾股'],
          guardrails: ['财报滞后，不能和未来公告数据混用；需要按报告披露日生效。'],
          sourceFrameworks: ['Fama-French Profitability', 'AQR Quality Minus Junk', 'MSCI Quality'],
        },
        {
          id: 'growth-acceleration',
          name: '成长加速度',
          category: '估值、质量与成长',
          horizon: '季度/年度财报',
          direction: 'higher_is_better',
          status: 'needs_data',
          priority: 3,
          formula: 'z(revenue_yoy) + z(net_profit_yoy) + z(delta_net_profit_yoy)',
          rationale: '成长因子更适合科技、消费和周期复苏阶段，和动量叠加能识别“业绩确认后的趋势”。',
          currentData: [],
          missingData: ['营收同比', '归母净利润同比', '扣非净利润同比', '分析师一致预期'],
          enrichmentPlan: ['补财报指标，并保留公告日、报告期和更新批次。'],
          useCases: ['成长动量', '业绩确认后的趋势候选', '行业景气对比'],
          guardrails: ['小基数高增长需要过滤；财报披露前不得使用未来数据。'],
          sourceFrameworks: ['MSCI Growth', 'AQR Quality growth pillar'],
        },
      ],
    },
    {
      id: 'capital-flow-event',
      name: '资金流与事件',
      description: '补充 A 股短线交易中特有的资金、涨跌停和事件驱动信号。',
      factors: [
        {
          id: 'main-money-flow-continuity',
          name: '主力资金连续性',
          category: '资金流与事件',
          horizon: '1-5 交易日',
          direction: 'higher_is_better',
          status: 'needs_data',
          priority: 1,
          formula: 'z(main_net_inflow_1d) + z(sum(main_net_inflow_3d)) + z(sum(main_net_inflow_5d))',
          rationale: '短线接力最需要观察资金是否连续进入，单日大额流入很容易误判。',
          currentData: ['板块资金已有成交额/涨跌代理'],
          missingData: ['主力净流入', '超大单净额', '大单净额', 'DDE 大单金额', 'DDE 大单净量'],
          enrichmentPlan: ['优先调研东方财富资金流接口可用性；授权源不足时记录为 planned，不混用不明口径数据。'],
          useCases: ['DDE 涨停资金接力', '资金转弱退出', '板块龙头确认'],
          guardrails: ['不同数据源“大单”定义不一致，必须保留 provider 和口径。'],
          sourceFrameworks: ['A-share capital flow'],
        },
        {
          id: 'limit-up-continuation',
          name: '涨停延续性',
          category: '资金流与事件',
          horizon: '4-10 交易日',
          direction: 'event_driven',
          status: 'ready',
          priority: 2,
          formula: 'limit_up_count_4d + 0.5 * limit_up_count_10d - untradable_limit_penalty',
          rationale: '涨停代表情绪事件被激活，延续性要同时看最近涨停、是否开板可成交和回踩承接。',
          currentData: ['quant.stock_bars.limit_up', 'quant.stock_bars.limit_down', 'quant.stock_bars.is_st'],
          missingData: ['封单金额', '炸板次数', '一字板成交可得性'],
          enrichmentPlan: ['后续接入分钟线/盘口后补封单和炸板特征。'],
          useCases: ['涨停回踩延续', '接力候选过滤', '事件强度标记'],
          guardrails: ['涨停本身不是买点；当日涨停无法合理成交时必须剔除或降权。'],
          sourceFrameworks: ['A-share event momentum'],
        },
        {
          id: 'sector-flow-heat',
          name: '板块资金热度',
          category: '资金流与事件',
          horizon: '5-20 交易日',
          direction: 'higher_is_better',
          status: 'partial',
          priority: 3,
          formula: 'rising_ratio + amount_ratio_20d + strength_20d + proxy_net_amount_ratio',
          rationale: 'A 股个股短线强弱常受板块共振影响，板块维度能帮助识别不是孤立拉升的标的。',
          currentData: ['sector tags', 'quant.stock_bars.amount', 'quant.stock_bars.change_percent'],
          missingData: ['真实板块主力净流入', '板块成分历史变更'],
          enrichmentPlan: ['为板块资金结果做 Redis 缓存，并补真实资金流端点。'],
          useCases: ['板块龙头识别', '市场资金环境判断', '候选股行业降权'],
          guardrails: ['当前是代理口径，不能当作真实主力净流入。'],
          sourceFrameworks: ['Sector rotation', 'A-share capital flow proxy'],
        },
      ],
    },
    {
      id: 'composite-ranking',
      name: '综合排序',
      description: '把单因子组合成可解释的候选分，供股票池、选股和回测统一使用。',
      factors: [
        {
          id: 'qvm-composite',
          name: '质量-价值-动量综合分',
          category: '综合排序',
          horizon: '20-120 交易日 + 财报期',
          direction: 'higher_is_better',
          status: 'partial',
          priority: 1,
          formula: '0.4 * momentum_z + 0.3 * quality_z + 0.2 * value_z + 0.1 * liquidity_z',
          rationale: '把动量、质量和估值拆开后再组合，避免页面只有单一“强弱”视角，也能服务中短期持有。',
          currentData: ['momentum_z', 'liquidity_z', '部分 value_z'],
          missingData: ['quality_z', 'growth_z', '行业中性化后的 value_z'],
          enrichmentPlan: ['先落地价格和流动性分，再接财报质量，最后做行业中性化。'],
          useCases: ['股票池默认排序', '短中期候选池', '组合回测入口'],
          guardrails: ['组合权重必须通过样本外回测验证，不凭主观固定。'],
          sourceFrameworks: ['S&P QVM', 'MSCI systematic factors', 'AQR Quality'],
        },
        {
          id: 'short-term-tradeability-score',
          name: '短线可交易分',
          category: '综合排序',
          horizon: '1-20 交易日',
          direction: 'higher_is_better',
          status: 'ready',
          priority: 2,
          formula: 'trend_score + liquidity_score + event_score - risk_penalty - untradable_penalty',
          rationale: '用于回答“明天/今天候选”的宽域选股问题，强调能不能交易，而不是只看涨幅。',
          currentData: ['OHLCV', 'amount', 'turnover', 'limit_up/down', 'is_st', 'sector tags'],
          missingData: ['盘中流动性', '实时资金流'],
          enrichmentPlan: ['短期先基于日线和实时行情输出候选；接分钟线后细化买点。'],
          useCases: ['首页宽域选股', '短线候选推荐', '买入价格计划前置过滤'],
          guardrails: ['必须输出止损、目标价、放弃条件和数据日期，不给确定性买卖承诺。'],
          sourceFrameworks: ['A-share tradability', 'Momentum and liquidity composite'],
        },
      ],
    },
  ],
  strategyBlueprints: [
    {
      id: 'data-ready-short-term-candidates',
      name: '数据就绪短线候选',
      status: 'ready',
      horizon: '1-5 交易日',
      factorInputs: ['短线可交易分', '20/60 日相对强弱', '均线多头质量', '成交额与换手活跃度', '涨停延续性'],
      strategyIdea: '仅使用当前日线和证券主数据可稳定计算的因子，筛出短线候选，并给出买入区间、止损、目标价和放弃条件。',
      validationPath: ['按最近交易日做全 A 股票池截面排序', '剔除 ST、科创、北证、当日涨停不可成交样本', '回测 1/3/5 日持有与止损', '比较费用和滑点后的收益回撤'],
      riskControls: ['候选必须有成交额和换手覆盖', '不使用缺失的 DDE 字段', '输出数据日期和被剔除原因'],
    },
    {
      id: 'qvm-mid-term-holding',
      name: '质量价值动量中期持有',
      status: 'partial',
      horizon: '20-120 交易日',
      factorInputs: ['质量-价值-动量综合分', '复合估值便宜度', '20/60 日相对强弱', '20 日实现波动率', '60 日最大回撤'],
      strategyIdea: '先用动量和估值形成候选，再等待盈利质量和成长数据补齐后做行业中性综合分，适合中期持有和组合轮动。',
      validationPath: ['先以价格和估值可用字段生成 v0 排序', '补 ROE/毛利率/现金流质量后生成 v1 排序', '按行业中性分位做月度调仓回测', '对比买入持有和等权组合'],
      riskControls: ['财报字段必须按披露日生效', '估值极端值要 winsorize', '行业内比较优先于跨行业裸比较'],
    },
    {
      id: 'capital-flow-limit-up-relay',
      name: '资金流涨停接力',
      status: 'needs_data',
      horizon: '1-10 交易日',
      factorInputs: ['主力资金连续性', '涨停延续性', '板块资金热度', '突破确认质量', '成交额与换手活跃度'],
      strategyIdea: '用于资金流和盘口事件补齐后的接力策略，关注近期涨停、板块共振、主力资金连续净流入和可成交性。',
      validationPath: ['接入真实资金流后重算 DDE 3/5 日连续性', '区分一字板、开板和炸板样本', '回测次日/3日/5日收益和无法成交占比', '与无资金流版本对比增益'],
      riskControls: ['当前资金流代理不能当真实 DDE 使用', '涨停当日不直接生成买入', '必须记录资金流 provider 和更新时间'],
    },
    {
      id: 'low-vol-drawdown-defense',
      name: '低波回撤防守',
      status: 'ready',
      horizon: '20-60 交易日',
      factorInputs: ['20 日实现波动率', '60 日最大回撤', '均线多头质量', '成交额与换手活跃度'],
      strategyIdea: '在趋势仍然成立时优先选择波动和回撤更可控的股票，用于降低短中期候选的尾部风险。',
      validationPath: ['按趋势候选内低波和低回撤排序', '比较加入防守因子前后的最大回撤和胜率', '扫描波动阈值和回撤阈值', '检查过度过滤导致的空仓比例'],
      riskControls: ['低波不能替代停牌和跌停风险检查', '低成交额样本不允许因为低波获得高分', '必须保留趋势过滤'],
    },
  ],
  enrichmentPlan: [
    {
      id: 'daily-factor-worker',
      title: '日频衍生因子批处理',
      priority: 'P0',
      currentGap: 'MA、强弱、波动、回撤和流动性现在多为查询时计算，跨页面复用和分页排序不够快。',
      targetTables: ['quant.stock_factors', 'quant.platform_jobs'],
      providerOptions: ['TimescaleDB continuous aggregate', '本地 worker 批处理'],
      unlocks: ['股票池服务端排序', '宽域选股加速', '回测前置过滤'],
    },
    {
      id: 'valuation-financials',
      title: '估值与财报质量补数',
      priority: 'P1',
      currentGap: 'PE/PB/PS/PCF 已有部分来源，但 ROE、毛利率、现金流质量和成长同比缺表。',
      targetTables: ['quant.stock_factors', 'quant.financial_statements', 'quant.financial_indicators'],
      providerOptions: ['Baostock', 'AKShare', 'Tushare Pro 授权源'],
      unlocks: ['质量价值动量综合分', '中期持有过滤', '行业内估值对比'],
    },
    {
      id: 'capital-flow',
      title: '真实资金流与盘口事件',
      priority: 'P1',
      currentGap: '板块资金目前是成交额代理，个股 DDE/大单净额/封单炸板仍缺真实字段。',
      targetTables: ['quant.capital_flow_daily', 'quant.intraday_bars', 'quant.limit_event_snapshots'],
      providerOptions: ['东方财富资金流', 'AKShare 聚合接口', '授权 Level-2/商业源'],
      unlocks: ['DDE 涨停资金接力', '资金转弱退出', '板块资金真实排行'],
    },
    {
      id: 'industry-neutralization',
      title: '行业中性化与板块成分历史',
      priority: 'P2',
      currentGap: '当前板块标签多为最新状态，缺少历史成分和行业内分位。',
      targetTables: ['quant.security_industry_memberships', 'quant.factor_cross_section_ranks'],
      providerOptions: ['东方财富板块', '申万/中信行业映射', '手工维护行业字典'],
      unlocks: ['行业内强弱', '行业中性估值', '板块轮动回测'],
    },
  ],
};

export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  {
    id: 'dde-limit-up-money-selection',
    name: 'DDE 涨停资金接力选股',
    kind: 'stock_selection',
    family: '选股策略',
    status: 'research',
    capabilityId: 'strategy_research',
    description: '按“近期涨停 + DDE 大单持续流入 + 均线多头 + 今日强开上涨”筛选接力候选股，核心输出是候选列表、排序原因和禁止买入原因。',
    defaultSymbols: ['002156', '002555', 'a-share-stock-universe'],
    timeframe: '日线 · 当日扫描',
    backtestStrategyId: 'volume_price_breakout',
    backtestLimit: 1260,
    dataDependencies: [
      ...STRATEGY_BACKTEST_DEPENDENCIES,
      'quant.stock_bars.limit_up / is_st / open / close / previous_close',
      'quant.security_universe_members.exchange / concepts',
      '待接入 quant.dde_money_flow_daily',
    ],
    parameterSchema: [
      { key: 'limit_up_lookback_days', label: '涨停观察', value: 4, unit: '日', description: '近 4 日至少出现 1 次涨停。' },
      { key: 'dde_3d_amount_min', label: '近 3 日 DDE', value: '>0', description: '近 3 日 DDE 大单金额合计为正。' },
      { key: 'dde_5d_amount_min', label: '近 5 日 DDE', value: '>0', description: '近 5 日 DDE 大单金额合计为正。' },
      { key: 'ma_stack', label: '均线排列', value: 'MA5>MA10>MA20>MA30>MA60', description: '多头排列，并且收盘价在 MA5 之上。' },
      { key: 'sort_by', label: '排序', value: '大单净量降序', description: '优先看当日大单净量，其次看 3 日 DDE 强度。' },
    ],
    parameterScans: [{
      id: 'dde-selection-threshold-grid',
      name: 'DDE 阈值与涨停窗口扫描',
      status: 'blocked',
      objective: 'DDE 字段落库后，比较近 3/5 日 DDE 阈值、涨停窗口和均线排列对后续 1/3/5 日收益的影响。',
      grid: [
        { key: 'limit_up_lookback_days', values: [3, 4, 5], unit: '日' },
        { key: 'dde_3d_amount_min', values: [0, 1000, 3000], unit: '万' },
        { key: 'holding_days', values: [1, 3, 5], unit: '日' },
      ],
      metrics: ['命中数', '次日收益', '3日收益', '5日收益', '最大回撤', '胜率'],
      guardrails: ['DDE 数据缺失时不允许自动回测', '剔除当日涨停无法买入样本', '按大单净量降序输出候选'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v0.1',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['沉淀 DDE 涨停接力选股口径', '标注当前缺失的 DDE 数据依赖'],
      parameterSnapshot: { limit_up_lookback_days: 4, dde_3d_amount_min: 0, dde_5d_amount_min: 0 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_SELECTION_RISK_CONTROLS,
    evaluationMetrics: ['命中数', '次日收益', '3日收益', '5日收益', '胜率', '最大回撤', '换手与成交额覆盖'],
    limitations: STRATEGY_SELECTION_LIMITATIONS,
    selectionRules: [
      { label: '近 4 日涨停 >= 1', description: '候选股最近 4 个交易日至少有一次涨停。', dataStatus: 'ready' },
      { label: '剔除科创/北证/ST', description: '排除 688/8/4 开头、北交所和 ST 风险标的。', dataStatus: 'ready' },
      { label: '近 3 日 DDE 大单金额 > 0', description: '近 3 日主力大单资金合计为正。', dataStatus: 'needs_data' },
      { label: '均线多头排列', description: 'MA5、MA10、MA20、MA30、MA60 从上到下排列。', dataStatus: 'ready' },
      { label: '收盘价在 MA5 之上', description: '避免弱势反抽，要求价格仍站上短线趋势。', dataStatus: 'ready' },
      { label: '今日 DDE 大单金额 > 0', description: '当日仍有大单净流入，避免资金转弱。', dataStatus: 'needs_data' },
      { label: '今日开盘价 > 昨日收盘价', description: '强开确认情绪延续。', dataStatus: 'ready' },
      { label: '今日上涨且前一日未下跌', description: '过滤连续转弱和阴线破坏。', dataStatus: 'ready' },
      { label: '当日没有涨停', description: '避免筛出无法合理买入的一字或涨停封板。', dataStatus: 'ready' },
    ],
    rankingRules: ['大单净量降序', '近 3 日 DDE 大单金额降序', '涨停距今天数越近优先', '成交额和换手率必须满足最低流动性'],
    dataReadiness: {
      ready: STRATEGY_OHLCV_DATA_READY,
      missing: STRATEGY_DDE_DATA_MISSING,
      notes: ['这是最贴近当前需求的核心选股策略；DDE 落库前只能展示口径和部分日线过滤。'],
    },
    promptSeed: '基于全 A 股票池执行 DDE 涨停资金接力选股：近4日涨停至少1次、非科创北证ST、均线多头、股价在MA5之上、今日强开上涨、近3/5日DDE为正，并按大单净量降序输出候选。',
  },
  {
    id: 'limit-up-pullback-continuation-selection',
    name: '涨停回踩延续选股',
    kind: 'stock_selection',
    family: '选股策略',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '筛选近 10 日涨停后缩量回踩、未跌破趋势线、重新站上 MA5 的二次启动候选，适合在没有 DDE 时先用日线数据做可回测选股。',
    defaultSymbols: ['002156', '002555', 'a-share-stock-universe'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'ma_pullback_reclaim',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'limit_up_lookback_days', label: '涨停观察', value: 10, unit: '日', description: '近 10 日内至少一次涨停。' },
      { key: 'pullback_window', label: '回踩均线', value: 10, unit: '日', description: '回踩不有效跌破 MA10。' },
      { key: 'reclaim_line', label: '重新站上', value: 'MA5', description: '今日重新站上 MA5。' },
      { key: 'volume_ratio_max', label: '回踩量能', value: 0.85, description: '回踩阶段量能低于前期均量。' },
    ],
    parameterScans: [{
      id: 'limit-up-pullback-grid',
      name: '涨停回踩窗口扫描',
      status: 'available',
      objective: '比较涨停观察窗口、回踩均线和止损阈值对二次启动收益的影响。',
      grid: [
        { key: 'pullback_window', values: [10, 20, 30], unit: '日' },
        { key: 'trend_window', values: [50, 60, 90], unit: '日' },
        { key: 'stop_loss_pct', values: [6, 8, 10], unit: '%' },
      ],
      metrics: ['胜率', '最大回撤', '交易次数', '平均收益'],
      guardrails: ['必须剔除当日涨停无法成交样本', '观察回踩破位后的亏损', '只允许在股票池成员上运行'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['将涨停回踩选股映射到可运行的 MA 回踩再启动回测'],
      parameterSnapshot: { limit_up_lookback_days: 10, pullback_window: 10, stop_loss_pct: 8 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_SELECTION_RISK_CONTROLS,
    evaluationMetrics: ['命中数', '次日收益', '5日收益', '胜率', '最大回撤', '交易次数'],
    limitations: ['暂不含 DDE 资金确认，可作为 DDE 策略落库前的日线替代口径。', ...STRATEGY_COMMON_LIMITATIONS],
    selectionRules: [
      { label: '近 10 日涨停过', description: '近 10 个交易日至少出现一次涨停。', dataStatus: 'ready' },
      { label: '缩量回踩不破 MA10', description: '回踩阶段不有效跌破 MA10，量能低于前期均量。', dataStatus: 'ready' },
      { label: '今日重新站上 MA5', description: '短线重新转强，作为候选触发日。', dataStatus: 'ready' },
      { label: '非 ST/科创/北证', description: '规避涨跌幅制度和风险标的混杂。', dataStatus: 'ready' },
    ],
    rankingRules: ['今日涨幅降序', '距离最近涨停日越近优先', '成交额越高优先', '回踩幅度适中优先'],
    dataReadiness: {
      ready: STRATEGY_OHLCV_DATA_READY,
      missing: ['分时承接强弱', '盘口封单/炸板次数'],
      notes: ['可直接用现有日线库回测，但盘中承接质量仍需后续接入分钟线。'],
    },
    promptSeed: '筛选近 10 日涨停、缩量回踩不破 MA10、今日重新站上 MA5、非 ST/科创/北证的股票，并对候选执行 5 日持有与止损回测。',
  },
  {
    id: 'ma-stack-breakout-selection',
    name: '均线多头突破选股',
    kind: 'stock_selection',
    family: '选股策略',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '用 MA5/10/20/30/60 多头排列、价格突破近 20 日高点、成交额放大筛选强趋势候选。',
    defaultSymbols: ['002156', '300750', 'a-share-stock-universe'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'volume_price_breakout',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'ma_stack', label: '均线排列', value: 'MA5>MA10>MA20>MA30>MA60', description: '多头排列确认趋势。' },
      { key: 'breakout_window', label: '突破窗口', value: 20, unit: '日', description: '收盘价突破近 20 日高点。' },
      { key: 'volume_ratio', label: '放量倍数', value: 1.4, description: '成交量相对均量放大。' },
    ],
    parameterScans: [{
      id: 'ma-stack-breakout-grid',
      name: '多头突破扫描',
      status: 'available',
      objective: '比较突破窗口和放量阈值对强趋势选股的影响。',
      grid: [
        { key: 'breakout_window', values: [15, 20, 30], unit: '日' },
        { key: 'volume_ratio', values: [1.2, 1.4, 1.8] },
        { key: 'exit_window', values: [8, 10, 15], unit: '日' },
      ],
      metrics: ['总收益', '最大回撤', '夏普', '信号数量'],
      guardrails: ['成交量缺失样本必须降级', '过滤流动性不足', '检查追高回撤'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增均线多头突破选股口径'],
      parameterSnapshot: { breakout_window: 20, volume_ratio: 1.4, exit_window: 10 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_SELECTION_RISK_CONTROLS,
    evaluationMetrics: ['命中数', '突破后收益', '最大回撤', '夏普', '成交额覆盖'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    selectionRules: [
      { label: 'MA 多头排列', description: 'MA5 > MA10 > MA20 > MA30 > MA60。', dataStatus: 'ready' },
      { label: '突破 20 日高点', description: '今日收盘价突破近 20 日高点。', dataStatus: 'ready' },
      { label: '放量确认', description: '今日成交量高于均量阈值。', dataStatus: 'ready' },
      { label: '非涨停可买', description: '当日未涨停，避免无法成交。', dataStatus: 'ready' },
    ],
    rankingRules: ['20 日强弱降序', '成交额放大倍数降序', '收盘价相对 MA5 偏离不过高优先'],
    dataReadiness: {
      ready: STRATEGY_OHLCV_DATA_READY,
      missing: ['行业相对强弱排名'],
      notes: ['当前可用日线直接回测，后续可叠加行业强弱。'],
    },
    promptSeed: '从股票池筛选 MA5/10/20/30/60 多头、突破 20 日高点、放量、当日未涨停的强趋势股票，并按 20 日强弱排序。',
  },
  {
    id: 'atr-cost-entry-price-plan',
    name: 'ATR 成本控制买入策略',
    kind: 'trade_price',
    family: '买卖价格策略',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '对已经入选的股票，使用 ATR、MA5、前收盘和风险预算给出可接受买入区间、止损价和第一止盈价。',
    defaultSymbols: ['002156', '002555', '600916'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'atr_trailing_breakout',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'risk_per_trade_pct', label: '单笔风险', value: 1, unit: '%', description: '单笔最大亏损占账户比例。' },
      { key: 'atr_window', label: 'ATR 窗口', value: 14, unit: '日', description: '估算正常波动。' },
      { key: 'entry_atr_discount', label: '买入回撤', value: 0.35, description: '尽量在开盘后回落到 0.35 ATR 内买。' },
      { key: 'stop_atr_multiplier', label: '止损距离', value: 1.2, description: '跌破买入价 1.2 ATR 或 MA10 失效。' },
    ],
    parameterScans: [{
      id: 'atr-entry-plan-grid',
      name: 'ATR 买入/止损扫描',
      status: 'available',
      objective: '比较 ATR 止损距离和突破窗口对收益回撤比的影响。',
      grid: [
        { key: 'breakout_window', values: [20, 40, 60], unit: '日' },
        { key: 'atr_window', values: [10, 14, 20], unit: '日' },
        { key: 'atr_multiplier', values: [2, 2.5, 3] },
      ],
      metrics: ['收益回撤比', '最大回撤', '止损频率', '夏普'],
      guardrails: ['止损价必须先于目标价生成', '高开过多时放弃追买', '费用和滑点纳入比较'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增入场成本控制与 ATR 风险口径'],
      parameterSnapshot: { risk_per_trade_pct: 1, atr_window: 14, stop_atr_multiplier: 1.2 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_PRICE_RISK_CONTROLS,
    evaluationMetrics: ['建议买入区间', '止损价', '第一止盈价', '收益回撤比', '最大回撤'],
    limitations: STRATEGY_PRICE_LIMITATIONS,
    entryRules: [
      { label: '不追高开过多', description: '若开盘涨幅超过计划上限，等待回落或放弃。', dataStatus: 'ready' },
      { label: '买入区间贴近 MA5/前收', description: '买入价优先控制在 MA5 与前收附近，避免成本失控。', dataStatus: 'ready' },
      { label: 'ATR 给出容错', description: '用 14 日 ATR 估算合理回撤和止损距离。', dataStatus: 'ready' },
    ],
    exitRules: [
      { label: '跌破 MA10 或 1.2 ATR 止损', description: '趋势失败时先控制亏损。', dataStatus: 'ready' },
      { label: '上涨 2R 先减仓', description: '达到两倍风险收益比时锁定部分利润。', dataStatus: 'manual' },
      { label: '沿 MA5/MA10 趋势持有', description: '强趋势不急于卖出，用趋势线跟踪。', dataStatus: 'ready' },
    ],
    dataReadiness: {
      ready: [...STRATEGY_OHLCV_DATA_READY, 'ATR 可由 high/low/close 计算'],
      missing: ['分钟线成交分布', '盘口滑点'],
      notes: ['可直接为股票池候选给出日线级买入/止损/止盈计划。'],
    },
    promptSeed: '对已经通过选股的股票生成 ATR 成本控制买入计划：给出合理买入区间、止损价、第一止盈价、放弃追高条件和仓位风险。',
  },
  {
    id: 'limit-up-next-day-price-plan',
    name: '涨停次日入场价格策略',
    kind: 'trade_price',
    family: '买卖价格策略',
    status: 'research',
    capabilityId: 'strategy_research',
    description: '针对近期涨停候选，按次日开盘强弱、是否高开过度、是否回踩承接，生成买入区间和放弃条件。',
    defaultSymbols: ['002156', '002555', '002624'],
    timeframe: '日线 + 盘中待接入',
    backtestStrategyId: 'gap_reversal',
    backtestLimit: 1260,
    dataDependencies: [
      ...STRATEGY_BACKTEST_DEPENDENCIES,
      '待接入集合竞价成交额',
      '待接入分钟线/盘口承接',
    ],
    parameterSchema: [
      { key: 'open_gap_min_pct', label: '最低强开', value: 0.5, unit: '%', description: '开盘需高于昨日收盘。' },
      { key: 'open_gap_max_pct', label: '追高上限', value: 5, unit: '%', description: '高开过多不追。' },
      { key: 'pullback_buy_zone', label: '回踩买区', value: '前收~MA5', description: '等待回踩承接再买。' },
      { key: 'failure_exit', label: '失败退出', value: '跌破前收', description: '强势预期失败时退出。' },
    ],
    parameterScans: [{
      id: 'limit-up-next-day-grid',
      name: '涨停次日开盘区间扫描',
      status: 'blocked',
      objective: '分钟线和集合竞价数据接入后，比较不同高开区间、回踩买点和止损条件的收益回撤。',
      grid: [
        { key: 'open_gap_max_pct', values: [3, 5, 7], unit: '%' },
        { key: 'stop_loss_pct', values: [3, 5, 7], unit: '%' },
        { key: 'max_holding_days', values: [1, 3, 5], unit: '日' },
      ],
      metrics: ['次日收益', '3日收益', '胜率', '最大回撤', '无法成交占比'],
      guardrails: ['一字板不生成买点', '高开过多自动放弃', '跌破前收必须退出'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v0.1',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['沉淀涨停次日买入价格计划', '标注分钟线和竞价数据缺口'],
      parameterSnapshot: { open_gap_min_pct: 0.5, open_gap_max_pct: 5, stop_loss_pct: 5 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_PRICE_RISK_CONTROLS,
    evaluationMetrics: ['建议买入区间', '放弃追高条件', '止损价', '次日/3日收益', '无法成交占比'],
    limitations: STRATEGY_PRICE_LIMITATIONS,
    entryRules: [
      { label: '开盘价 > 昨收', description: '强开是最基础入场前提。', dataStatus: 'ready' },
      { label: '高开不超过 5%', description: '超过追高上限优先放弃，避免成本失控。', dataStatus: 'ready' },
      { label: '回踩前收或 MA5 承接', description: '需要分钟线确认回踩不破。', dataStatus: 'needs_data' },
    ],
    exitRules: [
      { label: '跌破前收退出', description: '强势预期失败。', dataStatus: 'ready' },
      { label: '冲高不封板分批止盈', description: '需要盘中价格和成交量确认。', dataStatus: 'needs_data' },
      { label: '尾盘走弱不隔夜', description: '短线接力失败避免隔夜风险。', dataStatus: 'manual' },
    ],
    dataReadiness: {
      ready: STRATEGY_OHLCV_DATA_READY,
      missing: ['集合竞价成交额', '分钟线回踩承接', '封单/炸板次数'],
      notes: ['可先用日线开盘价做粗筛；真实买点需要分钟线。'],
    },
    promptSeed: '针对近 4 日涨停候选生成次日买入计划：开盘高于昨收但不高开过多，等待回踩前收或 MA5 承接，跌破前收退出。',
  },
  {
    id: 'ma-stack-swing-sell-plan',
    name: '均线趋势卖出策略',
    kind: 'trade_price',
    family: '买卖价格策略',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '对已经持有或准备买入的趋势股，按 MA5/MA10、ATR 和分批止盈给出卖出计划。',
    defaultSymbols: ['002156', '300750', '600519'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'ma_crossover',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'fast_window', label: '短线趋势', value: 5, unit: '日', description: '强趋势持有线。' },
      { key: 'slow_window', label: '防守趋势', value: 10, unit: '日', description: '跌破后降低仓位。' },
      { key: 'take_profit_r', label: '首个止盈', value: 2, unit: 'R', description: '达到 2 倍风险收益比先减仓。' },
      { key: 'hard_stop_pct', label: '硬止损', value: 7, unit: '%', description: '单笔最大容忍亏损。' },
    ],
    parameterScans: [{
      id: 'ma-sell-plan-grid',
      name: '趋势卖出窗口扫描',
      status: 'available',
      objective: '比较 MA5/MA10/MA20 卖出线对利润保护和过早离场的影响。',
      grid: [
        { key: 'fast_window', values: [5, 10, 20], unit: '日' },
        { key: 'slow_window', values: [20, 30, 60], unit: '日' },
        { key: 'fee_bps', values: [3, 5, 10], unit: 'bps' },
      ],
      metrics: ['总收益', '最大回撤', '胜率', '交易次数'],
      guardrails: ['fast_window 必须小于 slow_window', '卖出规则必须先于回测固定', '不允许事后挑最高点卖出'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增趋势股卖出计划口径'],
      parameterSnapshot: { fast_window: 5, slow_window: 20, take_profit_r: 2 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_PRICE_RISK_CONTROLS,
    evaluationMetrics: ['止损价', '减仓价', '趋势卖出价', '最大回撤', '利润回吐'],
    limitations: STRATEGY_PRICE_LIMITATIONS,
    entryRules: [
      { label: '只服务已入选候选', description: '不单独产生选股信号。', dataStatus: 'manual' },
      { label: '买入价不高于计划上限', description: '成本超限则不启用该卖出计划。', dataStatus: 'ready' },
    ],
    exitRules: [
      { label: '跌破 MA10 降仓', description: '短线趋势变弱时降低风险。', dataStatus: 'ready' },
      { label: '跌破 MA20 清仓', description: '中期趋势破坏时退出。', dataStatus: 'ready' },
      { label: '达到 2R 先减仓', description: '先锁定部分利润，再跟踪趋势。', dataStatus: 'manual' },
      { label: '硬止损 7%', description: '防止单笔亏损扩散。', dataStatus: 'ready' },
    ],
    dataReadiness: {
      ready: STRATEGY_OHLCV_DATA_READY,
      missing: ['盘中止盈触发价格', '真实滑点'],
      notes: ['可用当前日线数据评估卖出规则的收益回撤表现。'],
    },
    promptSeed: '为候选股票生成均线趋势卖出策略：买入成本、MA10 降仓、MA20 清仓、2R 分批止盈和硬止损价。',
  },
  {
    id: 'dde-flow-failure-exit-plan',
    name: 'DDE 资金转弱退出策略',
    kind: 'trade_price',
    family: '买卖价格策略',
    status: 'research',
    capabilityId: 'strategy_research',
    description: '对 DDE 选股后的持仓，若大单资金连续转负、价格跌破 MA5 或放量阴线，给出降仓/清仓计划。',
    defaultSymbols: ['002156', '002555', '002624'],
    timeframe: '日线 · 当日扫描',
    backtestStrategyId: 'momentum_trend',
    backtestLimit: 1260,
    dataDependencies: [
      ...STRATEGY_BACKTEST_DEPENDENCIES,
      '待接入 quant.dde_money_flow_daily',
    ],
    parameterSchema: [
      { key: 'dde_negative_days', label: 'DDE 转负', value: 2, unit: '日', description: '连续 2 日大单金额为负触发降仓。' },
      { key: 'price_break_line', label: '价格破位', value: 'MA5', description: '跌破 MA5 视为短线失效。' },
      { key: 'heavy_down_volume_ratio', label: '放量阴线', value: 1.5, description: '成交量放大且收阴时优先退出。' },
    ],
    parameterScans: [{
      id: 'dde-exit-grid',
      name: 'DDE 转弱退出扫描',
      status: 'blocked',
      objective: 'DDE 落库后比较连续转负天数、MA 破位和放量阴线对回撤控制的影响。',
      grid: [
        { key: 'dde_negative_days', values: [1, 2, 3], unit: '日' },
        { key: 'price_break_line', values: ['MA5', 'MA10', 'MA20'] },
        { key: 'heavy_down_volume_ratio', values: [1.2, 1.5, 2] },
      ],
      metrics: ['回撤降低', '利润回吐', '退出后收益', '误杀率'],
      guardrails: ['DDE 缺失时不允许自动退出回测', '不得用事后高点定义卖点', '必须展示误杀样本'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v0.1',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['沉淀 DDE 转弱退出规则', '等待 DDE 日频表落库'],
      parameterSnapshot: { dde_negative_days: 2, price_break_line: 'MA5', heavy_down_volume_ratio: 1.5 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_PRICE_RISK_CONTROLS,
    evaluationMetrics: ['资金转弱次数', '退出后收益', '回撤降低', '误杀率', '最大回撤'],
    limitations: STRATEGY_PRICE_LIMITATIONS,
    entryRules: [
      { label: '只用于 DDE 选股持仓', description: '不单独产生买入信号。', dataStatus: 'needs_data' },
    ],
    exitRules: [
      { label: 'DDE 连续 2 日转负降仓', description: '资金持续流出时降低风险。', dataStatus: 'needs_data' },
      { label: '跌破 MA5 清仓或降仓', description: '价格趋势破坏。', dataStatus: 'ready' },
      { label: '放量阴线优先退出', description: '量价共振转弱。', dataStatus: 'ready' },
    ],
    dataReadiness: {
      ready: STRATEGY_OHLCV_DATA_READY,
      missing: STRATEGY_DDE_DATA_MISSING,
      notes: ['这是 DDE 选股策略的配套退出模块，DDE 数据接入后价值最高。'],
    },
    promptSeed: '为 DDE 选股后的持仓生成退出策略：DDE 连续转负、跌破 MA5、放量阴线时降仓或清仓，并输出误杀风险。',
  },
  {
    id: 'ma-crossover-single-asset',
    name: '均线交叉趋势',
    family: '趋势跟随',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '用快慢均线交叉刻画趋势切换，适合先验证趋势品种和宽基 ETF 的可交易性。',
    defaultSymbols: ['002156', '510300', '601398'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'ma_crossover',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'fast_window', label: '快线窗口', value: 20, unit: '日', description: '短期趋势确认线。' },
      { key: 'slow_window', label: '慢线窗口', value: 60, unit: '日', description: '中期趋势过滤线。' },
      { key: 'fee_bps', label: '单边费用', value: 5, unit: 'bps', description: '买入和卖出分别扣减。' },
    ],
    parameterScans: [{
      id: 'ma-window-grid',
      name: '快慢均线鲁棒性扫描',
      status: 'available',
      objective: '验证趋势窗口是否对收益、回撤和换手过度敏感。',
      grid: [
        { key: 'fast_window', values: [10, 20, 30], unit: '日' },
        { key: 'slow_window', values: [50, 60, 90], unit: '日' },
        { key: 'fee_bps', values: [3, 5, 10], unit: 'bps' },
      ],
      metrics: ['总收益', '最大回撤', '夏普', '交易次数', '胜率'],
      guardrails: ['fast_window 必须小于 slow_window', '费用变化纳入对比', '拒绝只看收益最高参数'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v2.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['接入通用策略回测端点', '默认回测窗口扩展到近 5 年'],
      parameterSnapshot: { fast_window: 20, slow_window: 60, fee_bps: 5 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['总收益', '基准收益', '最大回撤', '夏普', '胜率', '交易次数', '暴露时间'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '对 002156 执行 20/60 均线交叉趋势回测，比较收益、回撤、夏普、交易次数和参数鲁棒性。',
  },
  {
    id: 'donchian-breakout',
    name: 'Donchian 通道突破',
    family: '突破交易',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '突破过去 N 日高点进场、跌破短通道低点退出，适合检验趋势延续和假突破成本。',
    defaultSymbols: ['002156', '300750', '510300'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'donchian_breakout',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'breakout_window', label: '突破通道', value: 20, unit: '日', description: '以前高作为入场阈值。' },
      { key: 'exit_window', label: '退出通道', value: 10, unit: '日', description: '以短低点作为失效线。' },
      { key: 'fee_bps', label: '单边费用', value: 5, unit: 'bps', description: '控制高换手策略成本。' },
    ],
    parameterScans: [{
      id: 'donchian-window-grid',
      name: '通道长度扫描',
      status: 'available',
      objective: '观察突破窗口和退出窗口对信号质量、持仓时长和回撤的影响。',
      grid: [
        { key: 'breakout_window', values: [20, 40, 60], unit: '日' },
        { key: 'exit_window', values: [10, 20, 30], unit: '日' },
        { key: 'fee_bps', values: [3, 5, 10], unit: 'bps' },
      ],
      metrics: ['总收益', '最大回撤', '夏普', '交易次数'],
      guardrails: ['退出窗口不能长于突破窗口', '检查信号过密导致的费用侵蚀', '必须展示亏损交易占比'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增 Donchian 通道实际回测引擎'],
      parameterSnapshot: { breakout_window: 20, exit_window: 10, fee_bps: 5 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['突破后收益', '最大回撤', '夏普', '平均持仓天数', '交易次数'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '用 Donchian 20/10 通道回测 002156，重点判断假突破、回撤和交易频率。',
  },
  {
    id: 'turtle-trend-following',
    name: '海龟中期趋势',
    family: '趋势跟随',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '55 日突破、20 日退出的中期趋势策略，用来评估强趋势资产的持有价值。',
    defaultSymbols: ['510300', '600519', '300750'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'turtle_trend',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'breakout_window', label: '入场通道', value: 55, unit: '日', description: '中期新高触发。' },
      { key: 'exit_window', label: '退出通道', value: 20, unit: '日', description: '趋势破坏退出。' },
      { key: 'fee_bps', label: '单边费用', value: 5, unit: 'bps', description: '长期持仓仍需扣减。' },
    ],
    parameterScans: [{
      id: 'turtle-window-grid',
      name: '海龟窗口扫描',
      status: 'available',
      objective: '比较 40/55/80 日突破和 10/20/30 日退出的趋势捕获能力。',
      grid: [
        { key: 'breakout_window', values: [40, 55, 80], unit: '日' },
        { key: 'exit_window', values: [10, 20, 30], unit: '日' },
        { key: 'fee_bps', values: [3, 5, 10], unit: 'bps' },
      ],
      metrics: ['总收益', '最大回撤', '夏普', '暴露时间'],
      guardrails: ['重点看长时间空仓风险', '不允许只用单一年份判断策略', '必须对比基准买入持有'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增海龟趋势参数口径和回测端点'],
      parameterSnapshot: { breakout_window: 55, exit_window: 20, fee_bps: 5 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['趋势捕获收益', '最大回撤', '空仓比例', '交易次数', '夏普'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '对 510300 执行 55/20 海龟趋势回测，说明中期突破相比买入持有是否改善回撤。',
  },
  {
    id: 'volume-price-breakout',
    name: '放量价格突破',
    family: '量价策略',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '要求价格突破同时成交量超过均量倍数，过滤无量假突破，适合个股题材行情验证。',
    defaultSymbols: ['002156', '002555', '002624'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'volume_price_breakout',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'breakout_window', label: '突破通道', value: 20, unit: '日', description: '价格突破观察窗口。' },
      { key: 'volume_ratio', label: '放量倍数', value: 1.4, description: '相对过去均量的确认阈值。' },
      { key: 'exit_window', label: '退出通道', value: 10, unit: '日', description: '跌破短低点退出。' },
    ],
    parameterScans: [{
      id: 'volume-price-grid',
      name: '量价确认扫描',
      status: 'available',
      objective: '验证放量阈值是否能减少假突破并改善回撤收益比。',
      grid: [
        { key: 'breakout_window', values: [15, 20, 30], unit: '日' },
        { key: 'volume_ratio', values: [1.2, 1.4, 1.8] },
        { key: 'exit_window', values: [8, 10, 15], unit: '日' },
      ],
      metrics: ['总收益', '最大回撤', '夏普', '信号数量'],
      guardrails: ['成交量缺失样本必须降级', '观察高换手和费用侵蚀', '避免只筛选热门股'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['接入成交量过滤的突破回测'],
      parameterSnapshot: { breakout_window: 20, volume_ratio: 1.4, exit_window: 10 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['突破胜率', '交易次数', '最大回撤', '夏普', '费用敏感性'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '回测 002156 的放量突破策略，比较 1.2/1.4/1.8 倍量能阈值对假突破的过滤效果。',
  },
  {
    id: 'atr-trailing-breakout',
    name: 'ATR 突破追踪',
    family: '波动率风控',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '突破入场后用 ATR 追踪止损，关注趋势跟随中的利润保护和波动适配。',
    defaultSymbols: ['002156', '600519', '510300'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'atr_trailing_breakout',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'breakout_window', label: '突破窗口', value: 20, unit: '日', description: '新高入场窗口。' },
      { key: 'atr_window', label: 'ATR 窗口', value: 14, unit: '日', description: '波动率估计窗口。' },
      { key: 'atr_multiplier', label: 'ATR 倍数', value: 2.5, description: '追踪止损距离。' },
    ],
    parameterScans: [{
      id: 'atr-trailing-grid',
      name: 'ATR 追踪参数扫描',
      status: 'available',
      objective: '比较止损距离对趋势持有、回撤和过早离场的影响。',
      grid: [
        { key: 'breakout_window', values: [20, 40, 60], unit: '日' },
        { key: 'atr_window', values: [10, 14, 20], unit: '日' },
        { key: 'atr_multiplier', values: [2, 2.5, 3] },
      ],
      metrics: ['总收益', '最大回撤', '夏普', '暴露时间'],
      guardrails: ['必须展示止损过紧导致的交易次数', '检查极端波动期表现', '不得忽略费用'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增 ATR 追踪止损回测'],
      parameterSnapshot: { breakout_window: 20, atr_window: 14, atr_multiplier: 2.5 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['最大回撤', '止损频率', '收益回撤比', '夏普', '暴露时间'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '对 002156 执行 ATR 突破追踪策略，重点解释止损倍数对回撤和收益的影响。',
  },
  {
    id: 'rsi-trend-reversion',
    name: 'RSI 趋势回撤反转',
    family: '均值回归',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '在中期趋势向上时买入 RSI 回撤，反弹到阈值或跌破趋势线退出。',
    defaultSymbols: ['601398', '600519', '002156'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'rsi_reversion',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'rsi_window', label: 'RSI 窗口', value: 14, unit: '日', description: '衡量短期超卖。' },
      { key: 'entry_rsi', label: '入场 RSI', value: 35, description: '低于阈值视作回撤。' },
      { key: 'exit_rsi', label: '退出 RSI', value: 55, description: '反弹到阈值止盈。' },
    ],
    parameterScans: [{
      id: 'rsi-reversion-grid',
      name: 'RSI 阈值扫描',
      status: 'available',
      objective: '验证超卖买入和反弹退出阈值对胜率、回撤和交易频率的影响。',
      grid: [
        { key: 'rsi_window', values: [10, 14, 20], unit: '日' },
        { key: 'entry_rsi', values: [30, 35, 40] },
        { key: 'exit_rsi', values: [50, 55, 60] },
      ],
      metrics: ['胜率', '最大回撤', '交易次数', '总收益'],
      guardrails: ['只在趋势过滤条件下入场', '检查连续下跌行情失效', '必须展示亏损交易'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增 RSI 趋势回撤回测'],
      parameterSnapshot: { rsi_window: 14, entry_rsi: 35, exit_rsi: 55 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['胜率', '平均交易收益', '最大回撤', '交易次数', '夏普'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '回测 601398 的 RSI 趋势回撤策略，判断低波动金融股是否适合超卖反弹交易。',
  },
  {
    id: 'bollinger-mean-reversion',
    name: '布林带均值回归',
    family: '均值回归',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '价格跌破下轨时买入，回归中轨附近退出，用于评估震荡品种的反转机会。',
    defaultSymbols: ['601398', '510300', '600519'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'bollinger_reversion',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'lookback_window', label: '布林窗口', value: 20, unit: '日', description: '均值和标准差估计窗口。' },
      { key: 'entry_z', label: '入场 Z 值', value: 2, description: '低于负 Z 值触发。' },
      { key: 'exit_z', label: '退出 Z 值', value: 0, description: '回到中轨附近退出。' },
    ],
    parameterScans: [{
      id: 'bollinger-grid',
      name: '布林参数扫描',
      status: 'available',
      objective: '比较均值窗口和入场偏离倍数对反转胜率与回撤的影响。',
      grid: [
        { key: 'lookback_window', values: [20, 30, 40], unit: '日' },
        { key: 'entry_z', values: [1.5, 2, 2.5] },
        { key: 'exit_z', values: [-0.2, 0, 0.3] },
      ],
      metrics: ['胜率', '最大回撤', '交易次数', '夏普'],
      guardrails: ['必须警惕趋势下跌中的接刀风险', '观察连续亏损', '比较不同波动窗口'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增布林带均值回归回测'],
      parameterSnapshot: { lookback_window: 20, entry_z: 2, exit_z: 0 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['胜率', '最大回撤', '连续亏损', '平均持仓天数', '夏普'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '对 510300 回测布林带均值回归策略，重点分析震荡和趋势阶段的表现差异。',
  },
  {
    id: 'momentum-trend-filter',
    name: '动量趋势过滤',
    family: '强弱动量',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '要求中期收益为正且价格在长期均线上方，适合检验强者恒强逻辑。',
    defaultSymbols: ['002156', '300750', '600519'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'momentum_trend',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'momentum_window', label: '动量窗口', value: 60, unit: '日', description: '衡量区间强弱。' },
      { key: 'trend_window', label: '趋势过滤', value: 120, unit: '日', description: '长期均线过滤。' },
      { key: 'min_momentum_pct', label: '最低动量', value: 8, unit: '%', description: '入场所需区间收益。' },
    ],
    parameterScans: [{
      id: 'momentum-trend-grid',
      name: '动量阈值扫描',
      status: 'available',
      objective: '比较动量窗口和最低动量阈值对趋势品种筛选效果的影响。',
      grid: [
        { key: 'momentum_window', values: [40, 60, 90], unit: '日' },
        { key: 'trend_window', values: [90, 120, 180], unit: '日' },
        { key: 'min_momentum_pct', values: [5, 8, 12], unit: '%' },
      ],
      metrics: ['总收益', '最大回撤', '暴露时间', '夏普'],
      guardrails: ['必须对比买入持有', '检查追高后的回撤', '观察空仓时间过长问题'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增动量趋势过滤回测'],
      parameterSnapshot: { momentum_window: 60, trend_window: 120, min_momentum_pct: 8 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['强弱收益', '最大回撤', '暴露时间', '夏普', '交易次数'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '对 002156 执行 60 日动量 + 120 日趋势过滤回测，比较不同动量阈值。',
  },
  {
    id: 'low-volatility-trend',
    name: '低波动趋势持有',
    family: '波动率风控',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '只在价格高于趋势均线且年化波动较低时持有，用于降低趋势策略中的噪声交易。',
    defaultSymbols: ['601398', '510300', '600519'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'low_volatility_trend',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'trend_window', label: '趋势窗口', value: 60, unit: '日', description: '持有趋势过滤。' },
      { key: 'vol_window', label: '波动窗口', value: 20, unit: '日', description: '年化波动估计。' },
      { key: 'max_volatility_pct', label: '最高波动', value: 35, unit: '%', description: '入场波动上限。' },
    ],
    parameterScans: [{
      id: 'low-vol-trend-grid',
      name: '低波趋势扫描',
      status: 'available',
      objective: '验证波动率上限是否能降低回撤，同时保留趋势收益。',
      grid: [
        { key: 'trend_window', values: [40, 60, 90], unit: '日' },
        { key: 'vol_window', values: [15, 20, 30], unit: '日' },
        { key: 'max_volatility_pct', values: [25, 35, 45], unit: '%' },
      ],
      metrics: ['最大回撤', '夏普', '暴露时间', '总收益'],
      guardrails: ['检查过度空仓', '波动阈值不可只服务单一历史区间', '必须展示基准收益'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增低波动趋势持有回测'],
      parameterSnapshot: { trend_window: 60, vol_window: 20, max_volatility_pct: 35 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['夏普', '最大回撤', '暴露时间', '波动过滤效果', '总收益'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '对 601398 回测低波动趋势持有策略，评估它是否能改善金融股的收益回撤比。',
  },
  {
    id: 'ma-pullback-reclaim',
    name: '均线回踩再启动',
    family: '趋势回撤',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '在长期趋势上行时等待回踩短均线后重新站上，捕捉趋势中的二次启动。',
    defaultSymbols: ['002156', '002555', '600519'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'ma_pullback_reclaim',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'pullback_window', label: '回踩均线', value: 20, unit: '日', description: '短线回踩和重新站上。' },
      { key: 'trend_window', label: '趋势均线', value: 60, unit: '日', description: '长期趋势过滤。' },
      { key: 'stop_loss_pct', label: '止损阈值', value: 8, unit: '%', description: '单笔最大容忍亏损。' },
    ],
    parameterScans: [{
      id: 'pullback-reclaim-grid',
      name: '回踩再启动扫描',
      status: 'available',
      objective: '比较回踩均线和趋势均线组合对二次启动交易的影响。',
      grid: [
        { key: 'pullback_window', values: [10, 20, 30], unit: '日' },
        { key: 'trend_window', values: [50, 60, 90], unit: '日' },
        { key: 'stop_loss_pct', values: [6, 8, 10], unit: '%' },
      ],
      metrics: ['胜率', '最大回撤', '交易次数', '平均收益'],
      guardrails: ['必须观察趋势破坏后的止损', '防止震荡市场反复交易', '费用纳入计算'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增均线回踩再启动回测'],
      parameterSnapshot: { pullback_window: 20, trend_window: 60, stop_loss_pct: 8 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['胜率', '最大回撤', '单笔亏损', '交易次数', '夏普'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '对 002156 回测均线回踩再启动策略，解释它和普通突破策略的差异。',
  },
  {
    id: 'gap-reversal',
    name: '跳空回补反转',
    family: '事件型反转',
    status: 'ready',
    capabilityId: 'backtest_review',
    description: '大幅低开但日内收复时买入，持有有限天数，检验恐慌低开后的短线回补。',
    defaultSymbols: ['002555', '002624', '002156'],
    timeframe: '日线 · 近 5 年',
    backtestStrategyId: 'gap_reversal',
    backtestLimit: 1260,
    dataDependencies: STRATEGY_BACKTEST_DEPENDENCIES,
    parameterSchema: [
      { key: 'gap_down_pct', label: '低开阈值', value: 3, unit: '%', description: '相对前收盘低开幅度。' },
      { key: 'max_holding_days', label: '最长持有', value: 5, unit: '日', description: '短线反转最大等待时间。' },
      { key: 'stop_loss_pct', label: '止损阈值', value: 6, unit: '%', description: '反转失败退出。' },
    ],
    parameterScans: [{
      id: 'gap-reversal-grid',
      name: '跳空回补扫描',
      status: 'available',
      objective: '验证低开幅度、最长持有天数和止损阈值对短线回补交易的影响。',
      grid: [
        { key: 'gap_down_pct', values: [2, 3, 4], unit: '%' },
        { key: 'max_holding_days', values: [3, 5, 8], unit: '日' },
        { key: 'stop_loss_pct', values: [4, 6, 8], unit: '%' },
      ],
      metrics: ['胜率', '平均收益', '最大回撤', '交易次数'],
      guardrails: ['只用于日线信号研究，不模拟盘中成交', '检查样本数量是否足够', '必须展示失败交易'],
      sampleSize: 27,
    }],
    versions: [{
      version: 'v1.0',
      status: 'active',
      updatedAt: '2026-05-29T00:00:00.000Z',
      changes: ['新增跳空回补反转回测'],
      parameterSnapshot: { gap_down_pct: 3, max_holding_days: 5, stop_loss_pct: 6 },
    }],
    backtestArchives: [],
    riskControls: STRATEGY_COMMON_RISK_CONTROLS,
    evaluationMetrics: ['胜率', '平均收益', '最大回撤', '交易次数', '持有天数'],
    limitations: STRATEGY_COMMON_LIMITATIONS,
    promptSeed: '对 002555 回测跳空回补反转策略，确认样本数量、胜率和单笔亏损是否可接受。',
  },
];
