import { SAMPLE_UNIVERSE_ID, SAMPLE_UNIVERSE_MEMBER_SEEDS } from './strategy-catalog';
import type { StrategyUniverseMember, StrategyResearchState } from './strategy-types';
import { inferSampleSectorTags, dataStatus, trendStatus } from './strategy-mappers';

const SAMPLE_UNIVERSE_MEMBERS: StrategyUniverseMember[] = SAMPLE_UNIVERSE_MEMBER_SEEDS.map((member) => ({
  ...member,
  concepts: [],
  sectorTags: inferSampleSectorTags(member.name),
  assetType: 'stock',
  currency: 'CNY',
  timezone: 'Asia/Shanghai',
  provider: 'eastmoney',
  securityStatus: 'active',
  role: 'member',
  weight: Number((1 / SAMPLE_UNIVERSE_MEMBER_SEEDS.length).toFixed(8)),
  rowCount: 0,
  latestClose: null,
  latestChangePct: null,
  latestAmount: null,
  latestTurnover: null,
  strength20dPct: null,
  strength60dPct: null,
  ma20: null,
  ma60: null,
  trendStatus: 'insufficient',
  avgAmount20d: null,
  avgVolume20d: null,
  avgTurnover20d: null,
  tradeStatus: null,
  isSt: null,
  limitUp: null,
  limitDown: null,
  peTtm: null,
  pbMrq: null,
  psTtm: null,
  pcfNcfTtm: null,
  dataStatus: 'missing',
}));

export const FALLBACK_RESEARCH_STATE: StrategyResearchState = {
  primaryUniverseId: SAMPLE_UNIVERSE_ID,
  source: 'fallback',
  universes: [
    {
      id: SAMPLE_UNIVERSE_ID,
      name: 'A 股股票池',
      description: '用于策略平台打通本地行情覆盖、数据质量检查和回测链路的默认股票池。',
      status: 'active',
      source: 'seed',
      tags: ['A股', '股票', '东方财富', '策略回测'],
      defaultTimeframe: 'daily',
      defaultAdjustment: 'qfq',
      provider: 'eastmoney',
      members: SAMPLE_UNIVERSE_MEMBERS,
      memberCount: SAMPLE_UNIVERSE_MEMBERS.length,
      stockCount: SAMPLE_UNIVERSE_MEMBERS.length,
      etfCount: 0,
      indexCount: 0,
      fundCount: 0,
      readyCount: 0,
      barCount: 0,
      latestTs: null,
    },
    {
      id: 'etf-index-pool',
      name: 'ETF/指数池',
      description: '用于指数代理、ETF 轮动和跨资产对比的独立池。',
      status: 'active',
      source: 'seed',
      tags: ['ETF', '指数', '东方财富', '轮动'],
      defaultTimeframe: 'daily',
      defaultAdjustment: 'qfq',
      provider: 'eastmoney',
      members: [],
      memberCount: 0,
      stockCount: 0,
      etfCount: 0,
      indexCount: 0,
      fundCount: 0,
      readyCount: 0,
      barCount: 0,
      latestTs: null,
    },
  ],
  coverage: SAMPLE_UNIVERSE_MEMBERS.map((member) => ({
    symbol: member.symbol,
    name: member.name,
    timeframe: 'daily',
    adjustment: 'qfq',
    provider: 'eastmoney',
    rowCount: 0,
    dataStatus: 'missing',
  })),
  ingestionPlan: {
    provider: 'eastmoney',
    universeId: SAMPLE_UNIVERSE_ID,
    timeframe: 'daily',
    adjustment: 'qfq',
    suggestedLimit: 1260,
    lookbackYears: 5,
    endpoints: [
      'GET /api/v1/research/universes/summary',
      'GET /api/v1/research/universes/{id}/members',
      'POST /api/v1/ingestion/eastmoney/history',
      'POST /api/v1/ingestion/akshare/history',
      'POST /api/v1/ingestion/baostock/history',
    ],
    guardrails: [
      '默认保留近 5 年前复权日线，保证策略回测读取同一价格口径。',
      '每次同步按 symbol/timeframe/adjustment/ts 幂等 upsert。',
      '历史样本不因后续补数被删除，回测窗口由查询条件决定。',
      '回测必须读取本地 TimescaleDB，避免外部行情变化影响复现。',
    ],
  },
};
